export const EXAM_LIST_REQUEST = 'EXAM_LIST_REQUEST'
export const EXAM_LIST_SUCCESS= 'EXAM_LIST_SUCCESS'
export const EXAM_LIST_FAIL= 'EXAM_LIST_FAIL'

export const EXAM_DETAILS_REQUEST = 'EXAM_DETAILS_REQUEST'
export const EXAM_DETAILS_SUCCESS= 'EXAM_DETAILS_SUCCESS'
export const EXAM_DETAILS_FAIL= 'EXAM_DETAILS_FAIL'